== Bitcoin Design Principles

_This talk was delivered in June 2015 at the Harvard Innovation Lab in Boston, Massachusetts, as part of an IDEO Lab design workshop. During this two-day workshop, students competed to create prototype applications based on bitcoin and blockchains._

Video Link: https://www.youtube.com/watch?v=Ur037LYsb8M

Good morning, everyone. Wow, what a difficult task you have. At a very basic level, you have to try to understand _what is bitcoin_. I can answer that question in four words. Bitcoin is digital money. But that doesn't really capture it. It's more like the internet of money. But really it's a consensus decentralized network based on blockchain technology and a proof-of-work algorithm that allows a digital token to act as a reward system for a game-theoretical competition between decentralized miners who validate—and "Oh my...,” it immediately goes off the cliff.

Even after a couple of years of exploring "What is bitcoin?" you'll find you're still learning, you're still trying to understand what it is. Part of the reason for that is because bitcoin is a really new technology, it's a really disruptive technology, but it also is an abstraction on a technology that is really old. That technology is money. Money is a tool, it's a technology. ((("money", "technology of")))It actually shares commonalities with linguistic structures, because we use it almost like a language to communicate value among ourselves in a society.

=== History of Money
Who wants to tell me here how old money is? _Audience member: “5,000?"_ Okay, that's a good guess. A bit older. Try again. The problem with trying to understand the history of money is that money is older than history. We can go and look at the writing about money. Money is older than writing. That may confuse you a bit. You're like, "Money's older than writing? That can't be.” In fact, if you look at the first forms of writing that we can find, they are spreadsheets. They are accounting ledgers. The first thing scratched onto tablets created with twigs and things like that are accounting ledgers. They represent how many amphorae of oil were given to the pharaoh. If you go even further back, we find ancient forms of money among the ruins of ancient civilizations: beads, feathers, shells, giant stones. Money has taken many forms, but it exists and has existed almost as long as language. This is a truly ancient technology. So, it's not 5,000 years. It's probably close to 500,000 years old.

==== Primates and Money
In fact, we see money emerge within other species. Highly intelligent species like primates, certain types of birds like crows, even marine mammals like dolphins have forms of tokens that they use to express value to each other. Or they can very quickly learn the mechanics of money. You can teach primates that if you turn in this pebble, you get a banana. And then watch, within a very short period of time, how that not only becomes a part of the primate culture but gets passed down to the next generation, and they start inventing economic activities. Not nice economic activities. They invent strong-armed robbery: beat up the other monkey and take its pebbles, so you can get bananas. They invent sexual favors for pebbles, so you can get bananas. They invent some of the earliest economic activities. ((("money", "animals use of"))) ((("innovation", "economic activities"))) ((("crime")))

____
"Highly intelligent species like primates, certain types of birds like crows, even marine mammals like dolphins have forms of tokens that they use to express value to each other."
____

Money is ancient, it’s an absolutely ancient technology, and none of us really understands it. If you want a demonstration of that fact, sit down and have a conversation with a four-year-old and try to explain money. You'll find out very quickly that the four-year-old has very good questions that you can't answer. You can watch parents go through this, it’s hilarious:

"Mommy, where does money come from?"
"The banks make it."
"How do they make it?"
"Well, they print it."
"Why can't we have more, then."
"Go clean your room."

You're about four questions from “Go clean your room” in a money conversation because adults don't really understand money. Even though it is a cultural artifact that has existed in our species for hundreds of thousands of years, we don't understand how it works.

=== Characteristics of Money
We've gone through several technological iterations of money. We started with very basic forms of money. These basic forms had certain unique characteristics that made them good as money. ((("money", "characteristics of")))What makes good money? Something that is rare. Shells, feathers. You can use shells as money, unless you live on a beach; if you live on a beach, you can't use shells as money. You can transport the value easily. So, it has to be portable. With few exceptions, most forms of money are highly portable. If the amount of money you need to go to buy a cow is heavier than the cow, that's not very good money. Which is why we don't often see, for example, gold being used for large transactions. It's too heavy. Other characteristics of money . . . It has to be difficult to forge; it has to be difficult to create more of it. You should be able to detect at a glance or relatively easily that it is real. It should be fungible. If I'm using shells, then this shell or that shell are both the same money. If I give you a dollar, it doesn't matter which dollar I gave you; it's fungible. Every dollar can substitute for every other dollar.

____
"Money itself is an abstraction. If it's not an abstraction, then it’s not money—it’s barter."
____

These are the technologies, and gradually over time we've created abstractions. Money itself is an abstraction. If it's not an abstraction, then it’s not money—it’s barter. If I give you bananas for your goat, that's not money. Bananas are not money because you eat them. You don't use them to do further exchanges. Therefore, that's barter.((("barter"))) You're exchanging one commodity for another. If it's abstract—if it doesn't have any practical use in itself—then as an abstraction of money it represents something else, some shared value. ((("money", "an abstraction")))

Which leads to the one inescapable conclusion about money: Money is a shared cultural hallucination. ((("money", "cultural hallucination")))It's a shared delusion. We walk around and associate with other people on the basis of germ-ridden pieces of cotton printed with green ink. If you were to observe that as an alien anthropologist that landed on Earth, you'd think it was very very weird. That just by exchanging these pieces of cotton, you could create social relationships, transactions, and trade— you could feed yourself, shelter yourself, etc., etc. It doesn't make much sense but it's based on a shared hallucination. It's based on the assumption that if you give me a dollar today, someone else will accept that dollar in exchange for something of value tomorrow. If I still believe that is the case, then it has value. Value comes from the assumption that I can use it again. ((("money", "value of")))

____
"Money is a shared cultural hallucination."
____

==== Just Another Abstraction of Money
Bitcoin is just the latest iteration of abstraction. We’ve done abstraction before but every time we do abstraction of money, society freaks out because this new thing can't possibly be real money. Go back and look at what happened with the introduction of coins stamped onto nonprecious metal, and then eventually paper notes. When paper notes were first circulated, no one believed that they had value. The shared hallucination had not taken hold yet. It was very difficult to persuade people to exchange real gold coins or silver coins for pieces of paper that said that they had gold in a vault. Then, take it a step further, and disappear the gold from the vault and say, "Turns out, it's just the paper."

____
"...every time we do abstraction of money, society freaks out because this new thing can't possibly be real money."
____

You ask people about bitcoin, and one of the first things I hear from most people is that it's not real money because it's not backed by gold like the US dollar—which I find astonishing. ((("money", "backed by gold")))The dollar hasn't been backed by gold since 1936. Yet, most people think that somewhere in the vault, possibly at Fort Knox or some other movie location, there are bars of gold that correspond ingot to ingot to the pieces of paper that you have in your pocket. They don't. There's no such thing. Why is bitcoin money? Because other people think it's money. You can write a dozen Ph.D. dissertations explaining exactly why bitcoin is not money . . . and I have lived on it for two years. Therefore, it doesn't matter what your dissertation says. To me, it is money, _because_ I have lived on it for two years. So have thousands of other people. Therefore, to me, it is very much real money.

=== Bitcoin and Design
You've been tasked with creating designs and concepts around the oldest technology in the world that very few people really understand. Its latest, most abstract expression, that is brand new, is completely disjointed from previous expressions of money and is extremely complex as a technology. That is a really difficult task. When faced with that task, your go-to technique is the use of metaphor. Design metaphors are extremely powerful tools. They allow us to create expectations. Metaphors are tools by which we create expectations. When you have a desktop computer and it has a desktop, you assume that something will happen when you drag something across the desktop. Because you've actually used a real desk, that assumption will inform your expectations. You expect it to behave like the object that it's pretending to be. That's a design metaphor. Design metaphors are extremely powerful, but they're also extremely dangerous when misapplied. ((("design", "metaphors")))

____
"Design metaphors are extremely powerful, but they're also extremely dangerous when misapplied. In bitcoin, every single term and design metaphor is wrong and broken."
____

==== Wallets Aren't Wallets
In bitcoin, every single term and design metaphor is wrong and broken. Let's go through the list. You've probably struggled with this as you've engaged with this technology of bitcoin and looked at all of the terminology. First of all, a “wallet.” ((("wallet")))What is a wallet? A wallet is something that stores money. Not in bitcoin it isn't. The money isn't in the wallet; the money is on the network. The wallet contains keys. So, it's not a wallet; it's a keychain. How can you tell it's not a wallet? Can you copy a wallet? No. But you can copy a key. A keychain is a far better metaphor. If I have a keychain—imagine a big ring of keys like a janitor or a custodian—I have a bunch of keys, and I can go into a shop and have all of those keys duplicated and create a second keychain. Both of those keychains will work interchangeably in all of the locks that the original keychain worked. ((("keys")))That's how a keychain works. If you understand what a keychain does, then you will understand how a bitcoin wallet works. You can copy it, you can make copies of the keys. If you give someone a copy of the key, they can open the door. They don't need your permission anymore to open the door. ((("keys", "permission")))

So, a “wallet” is not a wallet; it's a keychain. That’s a terrible metaphor. You have expectations of what a wallet will do. It will contain things. These contents will be discrete and enumerated. None of that exists in bitcoin.

==== No Coins in Bitcoin
Let's get down to basics: “Bit - coin.” _Coin_. What a terrible word. What a terrible brand. _Coin_. Take the most abstract form of money we have ever created, that is based on a completely decentralized network that has no coins, and then name it “bitcoin.” Just to confuse everyone. A coin, which is two generations of technology back and a far less abstract, much more tangible, physical representation of money. You took the most abstract representation of money and named it after the most tangible representation of money. Only an engineer could come up with that brand.

Here's a little secret: there are no coins in bitcoin. When miners mine, they don't create coins; they create ledger entries. Those ledger entries do not enumerate coins. They have outputs—transaction outputs—which are chunks of value that are infinitely divisible and recombinable. Coins don't do that. You can't track a coin in bitcoin because there are no coins.

So, you've got a “wallet” that doesn't contain “coins”—because the coins are actually on the network and they’re not coins, they’re outputs—and what you're really holding is a keychain. Transactions are not from a sender to a recipient. Addresses don't have balance in bitcoin. There's no such thing as a balance of an address. An address controls outputs, and if you trawl through the blockchain and add up all of the outputs, you can figure out some notional balance. Whether that's actually spendable or not, how much it is, is actually quite difficult to determine. There is no “balance.” You have no “account” in bitcoin.

All of the terms are broken. The problem is, from a design perspective, instead of the metaphor informing our expectations, it is misinforming our expectations. It is creating the grounds for massive misunderstanding, because we think it's going to do something in a certain way, and it ends up doing something completely different, something unexpected. Kind of like the Windows desktop. I don't know if you've ever compared a Mac and a Windows desktop. To me Windows desktops have no consistency. The metaphor is completely broken. You expect it to do one thing, it does something completely different and confuses. The essence of good design is picking the metaphor that informs expectations.

____
"The essence of good design is picking the metaphor that informs expectations."
____

==== Skeuomorphic Design
Here's the next big problem with metaphors and design. There's a certain concept called _skeuomorphic design_. ((("design", "skeuomorphic")))The word _skeuomorphic_ means “a shadow of its former self.” It's form as a shadow. What it means is when you create elements in design that give you references or hints of some previous form. For example, a classic example, in the first iteration of iPads, the iOS software had a lot of skeuomorphic design. If you opened your contact database, it was bound in leather. That leather had stitching. That stitching didn't do anything. It was just a design element which had no functional purpose, whose intent was to put you into a familiar set of mind so that you could understand the metaphor. When you're playing a card game on your computer and it has fake felt under the cards, that's because it's trying to draw out the metaphor of a casino by introducing this design element. Skeuomorphic design is extremely powerful. It's also extremely dangerous. If you don't use it correctly, again, it creates different expectations as to what is going to happen next.

In bitcoin, we have a lot of skeuomorphic design. My favorite and most hated form of skeuomorphic design is the picture you will see in every single article written about bitcoin: a pile of gold coins with a letter B on them, usually the Casascius coin designed by Mike Caldwell, but possibly some other rendering of that. Taking the worst design metaphor of bitcoin, the word “coin,” and then instantiating it in a beautiful rendering that makes it even more physical looking, in a skeuomorphic design that completely misleads everyone. People are actually going out on eBay and they're buying what they think is “bitcoin.” They're buying gold-plated, physical coins that have nothing to do with the blockchain but have the letter B stamped on them. "Look, I've joined the revolution of digital money" they say, but these tangible replicas rarely have any value in bitcoin. This is the result. Then, people write articles, and they look at the picture and they think, "So that's what a bitcoin looks like." That's not what a bitcoin looks like, because if you remember, I may have mentioned, there are no coins. This is the danger.

=== Designing for Innovation
It's a really difficult task to design good metaphors for bitcoin because there is no parallel. We have never done this before. We fall into these traps of trying to extrapolate from our previous experience, and fall short. Disruptive technologies do this. ((("design", "disruptive tech")))In an incremental technology, if you take what you currently understand and then just use a milligram of vision and extend it just a tiny bit, you understand the new technology because it really is just a slight extension of the past. ((("innovation", "incremental tech"))) Bitcoin is a radical break from the past, so understanding the way traditional money works doesn't help you understand bitcoin. If anything, it hinders your understanding of bitcoin. The people who understand bitcoin the least are monetary economists. They cannot wrap their heads around it. They will write long theses on how bitcoin is not money, despite the fact that I've been living on it for years.

____
"Bitcoin is a radical break from the past, so understanding the way traditional money works doesn't help you understand bitcoin."
____

Understanding disruptive technologies is even harder than understanding incremental technologies because the most interesting things they do have no previous parallel. ((("innovation", "disruptive tech"))) Think about it this way . . . Look back at _Star Trek_ in the 1970s. What did they get right? They got tricorders. They got portable communicators. They got video telephony. They got all that was predictable with the technology of the 1970s. They couldn't possibly get the internet. They couldn't possibly understand the idea of networked information stores. They had fantastical computers that could talk to you, but they didn't have access to any data. They couldn't possibly predict things like social media. Most importantly, if you pay attention, you will notice something very strange. _Star Trek_ doesn't have any money at all. There is no money anywhere in the _Star Trek_ universe. Why is that? Because their furthest vision of the possibility of society is a society without money, a society without a language for transmitting value, which is probably the most radical departure from reality.

==== Predicting the Future
When we try to predict the future, there are certain areas that are completely dark to us. These are the areas that have never been seen before. These are the applications that we cannot imagine because, in order for them to come into being, many things have to fall into place. For the web to happen, you needed a common standardized transmission protocol. For the web to give birth to social media, you needed massive penetration of basic email and TCP/IP connections. You needed penetration of those connections on an always-on state. You needed to have mobile devices with high-density computing in the palm of your hand that were internet connected. All of those things had to come to fruition before social media was even possible.

____
"If you look at the internet in 1992, you think that it will replace the phone. That's the only experience that you have."
____

If you look at the internet in 1992, you think that it will replace the phone. That's the only experience that you have. The internet is a fancy phone. Perhaps it's a fancy phone/fax, perhaps a multifunctional printer/fax/phone. It's very fancy. So, the phone companies look at this and say, "Oh, it's a fancy phone. We can do this." They were wrong, fortunately. Otherwise, every time I went on a Skype call, there would be a little slot on the side of my computer, and I would have to deposit quarters every three seconds to make a Skype call. Fortunately, the phone companies didn't get to write the rules. ((("innovation", "regulation")))They couldn't possibly predict the outcomes we saw on the internet, because most of the interesting things were not incremental improvements or extensions of the things before. They were radical departures from the past, because they created the conditions for things that were not possible before.

Let's go back to bitcoin and think about this for a second. Consider what we've been talking about: financial transactions, banking, payments. “It's a fancy credit card.” “It’s Paypal, basically. It's a global Paypal." But it's not. It's something completely, radically different, but we can't see where that’s going to go. The applications that are going to happen on bitcoin, the really interesting applications, are those that can only happen when you have sufficient adoption and penetration of this technology—the ability to do cross-border transactions on a level that has never been done in the history of humanity before.

____
"Consider what we've been talking about: financial transactions, banking, payments. 'It's a fancy credit card.' 'It’s Paypal, basically. It's a global Paypal.' But it's not. It's something completely, radically different."
____

Today, there are 3 billion people with no banking facilities whatsoever. Three billion more people—“underbanked,” as we call them—without any access to international credit or finance. ((("financial inclusion")))You or I can go to a brokerage website right now and within 24 hours have a US-dollar-denominated account that can trade on the Tokyo stock exchange. That is privilege. That is a facility afforded to less than a billion people in the world. One out of seven. The other 6 billion? They barely have basic checking, if that. A lot of them live in cash- or barter-based societies. So, the question you then have to ask is what happens when a farmer in Kenya who has a Nokia 1000 text-messaging phone, and suddenly that phone is a Bloomberg terminal, a loan-origination terminal, a Western Union remittance-termination terminal, a stock market, _is_ a bank—not a terminal to a bank, but a bank, on the phone? And what happens when that is afforded to the other 6 billion all over the world.

Part of the reason bitcoin is unstoppable is because there is this great need for this technology. Banks in the developing world cannot extend services to these populations. Recently, I was talking to a banker who told me, “Half our population is 100 miles from the nearest branch, upstream, on a canoe. We can't serve them.” But even the remotest village in the Amazonian basin has a cell phone tower, and someone in that village has a solar panel and a Nokia 1000 text phone. There are more Nokia feature phones in the world than any other kind of electronic device. It is the most massively produced device humanity has ever produced. Almost 5 billion people have access to cell phones. Almost 3 billion people have access to cell phones and do not have access to safe drinking water. Think about that. Cell phones are more widespread than water on our planet. What happens when each and every one of those is a banker. For me, the vision of bitcoin is not to bank the other 6 billion; it's to unbank all of us. ((("banking", "unbank")))We can do it. Banking is an app.

____
"For me, the vision of bitcoin is not to bank the other 6 billion; it's to unbank all of us."
____

=== Interstitial Innovation
That's just the beginning. The really interesting things in bitcoin happen in what I call “interstitial innovation”—the innovation in the gaps, the places where today's systems cannot go. ((("innovation", "interstitial")))Technologies have an interesting effect where they suddenly change basic assumptions. Some of the most powerful things that happen on the internet happen not just because of connectivity, but because of the marginal cost of transmitting information over distance. Before the internet, moving information from point A to point B cost a lot of money. The internet drove that cost almost to zero. The result was that millions of applications that could not happen on the previous cost basis, even if we could imagine them, suddenly became possible. Why on earth would you stream music instead of buy it and store it locally? Because it costs nothing. Once it costs nothing and you can stream music, then you suddenly realize that ownership is kind of overrated. If an entire generation realizes that, then intellectual property is kind of overrated. Bye-bye, recording industry. These effects happen because the technology changes the fundamental costs of doing things.

Let's think about what happens when bitcoin changes the fundamental cost of transacting—transacting across distance, transmitting value, recording information, and recording information in an immutable way. What happens when, for the first time ever, there is a system that can evaluate rules without human intervention and be trusted without having to put trust in any single human? In bitcoin, we call this the removal of counterparty risk. If I create a transaction and I sign it, everyone on the bitcoin network can validate that transaction independently. They don't have to ask anyone. They can go through the blockchain on their own machine, which they know is correct and true because they have been tracking it and building it based on proof of work. They can check that transaction, 350 bytes, and they can validate that transaction without asking anybody else. A self-verifying system, a system of rules that exists independent of human actors, that exists based on this network topology.

____
"What happens when, for the first time ever, there is a system that can evaluate rules without human intervention and be trusted without having to put trust in any single human? In bitcoin, we call this the removal of counterparty risk."
____

What does that mean? What does it do to commerce, to transactions? We can understand what it does to banking. We can understand that Western Union is going down hard this decade. You charge 30 percent on the poorest people in the world, you deserve to go down by disruptive technology. ((("remittances")))Last year, the CEO of Western Union said, “In the medium term, we are not worried about bitcoin." I want that framed on my wall. It's one of those phrases, like the boss of Kodak saying things like that when Nokia took away their lunch. Kodak was the largest camera company in the world until a company that wasn't in the camera business shipped a billion cameras in one year and destroyed their industry. They never saw it coming. Nokia, by the way, is the world's largest manufacturer of cameras, by far. That's going to happen to Western Union.

That's the easy stuff. What happens when you are able to do this validation of rules without a third party? It changes several fundamental societal institutions that we have today. It changes what's called the _Coase coefficient_, which is the overhead created by organization. If we want to do something as a team, two people can do more than what one person can do. Three people can achieve even more. But there's a limit to that. Once you get too big, the communication overhead between participants in the group is greater than the marginal increase in efficiency. So, adding more people makes it worse, because the group is getting bigger too fast. Bitcoin changes that, because it now reduces the coefficient of organizing on a transactional, on a commercial, on an independent-validation basis, on an extremely large scale. We can now get about a million people, about 5,000 machines, to agree on the state of a ledger every ten minutes at extremely low cost. That has never happened before. It opens the door for things that we can’t even imagine. Bitcoin is radically discontinuous from the past.

Let's take one simple example: personhood. Personhood is required for financial ownership. In order to own money, in order to control funds, in order to have a bank account, to receive a bill, to pay someone, you must be a person. Everywhere in the world in every payment and financial network that exists, people own money. They may own it in the form of corporations, but that's just people grouping together. They may use proxies, agents, things like that, but that's just people working together. Bitcoin does not require personhood. A software agent can own money. A piece of software can be autonomously controlling money without any human intervention. This is completely unheard of in the history of man. We have never seen what happens next.

Here's a little thought experiment: Let's take three radically disruptive technologies and mash them together. ((("innovation", "mash-up"))) Bitcoin. Uber. Self-driving cars. What happens when you mash the three together? The self-owning car. A car that pays for its Toyota lease, its insurance, and its gas, by giving people rides. A car that is not owned by a corporation. A car that _is_ a corporation. A car that is a shareholder and owner of its own corporation. A car that exists as an autonomous financial entity with no human ownership. ((("self-owning cars", "automobiles")))This has never happened before, and that's just the beginning. _Audience member gasps: "Oh shit!"_

____
"Let's take three radically disruptive technologies and mash them together. Bitcoin. Uber. Self-driving cars. What happens when you mash the three together? The self-owning car."
____

I can guarantee you that one of the first distributed autonomous corporations is going to be a fully autonomous, artificial-intelligence-based ransomware virus that will go out and rob people online of their bitcoin, and use that money to evolve itself to pay for better programming, to buy hosting, and to spread. That's one vision of the future. Another vision of the future is a digital autonomous charity. Imagine a system that takes donations from people, and using those donations it monitors social media like Twitter and Facebook. When a certain threshold is reached and it sees 100,000 people talking about a natural disaster, like a typhoon in the Philippines, it can marshal the donations and automatically fund aid in that area, without a board of directors, without shareholders. One hundred percent of donations goes directly to charitable causes. Anyone can see the rules by which that autonomous altruistic charity works. We are beginning to approach things we have never seen before. This is not just a currency.

Now, let's look at how the bitcoin community is addressing this incredible potential with their design choices and metaphors. Oh boy, it's a mess.

=== ATM Experience
Let's take a simple example. How many of you had an experience with a bitcoin ATM—or BTM, as it's known? ((("ATM")))How was that experience? Who enjoyed it? Nobody, that’s about right. What is an ATM? ATMs have been around for 25 years now. What purpose does an ATM serve? What is its goal? _Audience member: “It's a cash dispensary.”_ Okay. When you interact as a person with an ATM: you have a pre-existing relationship with the bank or financial institution, you have a pre-existing balance, your primary objective is to get in, get cash, get out. Twenty seconds is too long. Three clicks is too long. The most incredible innovation in ATMs in the last 25 years has been Fast Cash. That's it. They haven't really changed much. You press a button. Now, I can get cash in one click. Wow—15 seconds, in and out. Why is this important? Because one of the primary uses of ATMs is that at 1:00 in the afternoon, 100 people line up in front of four or five ATMs in the center of town and all try to take out 20 dollars to buy lunch. ((("design", "purpose")))You see this all around the world.

What is the purpose of an ATM? For a bank, the purpose of an ATM is reducing the overhead of having a human, and reducing the interaction to the shortest possible time for someone who has a pre-existing relationship with that bank. What does that have in common with the bitcoin ATM? Absolutely nothing.

=== Bitcoin ATM Experience
Now let's look at the experience of a bitcoin ATM. ((("design", "user experience")))The average user of a bitcoin ATM is someone who has never seen bitcoin before. It is a person who doesn't understand what bitcoin is, and the ATM is their first introduction to this currency. It's a person who does not have a pre-existing relationship with anyone in the bitcoin space. It is a person who does not currently have a wallet, because they didn't know they needed one. They don't know what a wallet is, they certainly don't know it’s actually a keychain. They walk up to this machine, and this machine has been designed by engineers to simulate the experience of an ATM, even though the experience shares absolutely nothing with the use case we're putting it to.

So, you walk up and the ATM tries to give you bitcoin in as few clicks as possible with a minimum amount of interaction. Is that a way to build brand loyalty? Is that a way to build user experience? Is that a way to introduce new users? I mean, it just throws it at you. You're not ready for that. _Please open your phone and display your QR code._ You’re like, “What? What's a QR code? . . . Hang on, let me go to Google Play and search for ‘QR code.’ There's an app that scans them, . . . maybe I should use that one. Shouldn't use that one. Maybe I should use a bitcoin wallet. Oh, there are 26 of them. Which one's the best? I don't know. I'll use Circle. . . . Oh, that requires a pre-existing relationship, whoops. I'll use Coinbase. . . . Oh, that requires a pre-existing relationship, oops. . . .”

Finally, I've got my wallet and I display the QR code, put some money in, and I've got the bitcoin. What am I going to do with it? I have all these questions. Who takes bitcoin? Where can I spend this? How do I send it? How do I secure it? Will it get lost if I lose my phone? I have no clue. Why? Because this bloody infernal machine didn't tell me anything. It just threw the bitcoin at me, and in 15 seconds it's off to the next customer.

If I was designing a bitcoin ATM, first of all, I'd put it in bodegas. Secondly, it wouldn't have a lick of English on it; it would be all Spanish because I'm going to really push the remittance model. Thirdly, the first function on the ATM would be _Send Money to Mexico City_. That's it. Because I want people to use the bitcoin for something. Fourth, I'd have a big button on the front that says _Talk to a Human_. I've got an internet-connected device with a forward-facing camera and a tablet screen, and I'm not using it to do video customer service, are you kidding me? Boom: Skype. A person. “What the hell is bitcoin? Where do I spend it?” "Oh, sir, I see that you're in the bodega on 25th Avenue. There are three stores that take bitcoin in your area. Let me show you a brief introductory video. Gather all the children in the store and we can all dance to a little bitcoin song. Let's watch another video.” I don't want to interact for 15 seconds. I want to interact for two hours and get all of my friends to sit in front of the machine and watch the little bitcoin videos and learn about bitcoin. It's got pretty colors, and it tells me where I can spend it. It gives me suggestions on wallets. It can send them directly to my phone. It's building loyalty, brand, and experience. That's not a 15-second interaction. This is the first experience that many people will have with bitcoin. You have the opportunity to make this a deep, meaningful, educational experience. But you don't.

=== Kids Use Bitcoin
Here's another little clue: kids are using bitcoin. On average around the world, the earliest age at which you can open a bank account is 16 years old. By the time that 16-year-old goes to the bank, I want them to have at least six years of active bitcoin use in their experience. Because then, when they face their first banker, they’re going to be, "Three to five days?! Business days?! What the hell is a business day? What do you _mean_ you close at 5:00? I barely get off of work at 5:00. What do you mean I have to pay for you to store my money. This is ridiculous. Have you people even heard of bitcoin?!” ((("banking", "the experience")))

____
"For many young people, bitcoin will be their first economic experience. By the time they get to a bank, they will be done with banking in advance."
____

That's the experience I want. Guess what? Ten-year-olds are opening bitcoin accounts. You know why? They can go download the app on the internet, and they can be in control of money for the first time. So, you need to have the birds-and-bees discussion, but you also need to have the private-keys discussion. This is a huge generational divide. For many young people, bitcoin will be their first economic experience. By the time they get to a bank, they will be done with banking in advance. That's a huge advantage.

=== Brand New Tech, Same Old Terms
So, how do you appeal to a completely new demographic? Part of the trick is not trying to be a bank. Do not try to do anything related to traditional banking. All that does is pollute their mind. You want new users to have a brand new experience with bitcoin that is unlike any banking they will ever see. You don't want it to look like a checking account. God forbid you use the word "checking.” Open any one of the exchanges right now—Circle, Coinbase. What is the name of your account on Coinbase? It is a checking account, and it has a balance, and it shows you a statement. Who did they hire for this design? What does the word “checking” mean? It means an account on which you can write checks. I know this is America and we're 25 years behind on fintech. The rest of the world doesn't do checks, I guarantee you. What is a check? A check is the device by which a grandma can make 20 people in line behind her in the supermarket simultaneously groan. I use it to pay my rent every month. I don't know why. I can't do it any other way. It's insane that I'm signing a piece of paper and sending it through the postal system in 2015. So that my landlord can walk it through the bank and deposit it. So that it might clear three to five business days later, after they've charged him five dollars to own his own money.

We don't really need a hard sell to make bitcoin win on the banks. All you need in order for bitcoin to win against banks is for a person to use bitcoin for a week, and then the bank will take care of the rest. They'll freeze their account, they'll tell them they're closed, they'll hold it for three to five business days. They just sold bitcoin. Banks will sell it for you every single time.((("user experience")))

==== The Joys of International Wire Transfer
I was invited to do a talk at the Bundesbank, the German Federal Bank. They were paying me for this speaking engagement, but they didn't know how to do bitcoin, which is a real problem because I usually get paid in bitcoin. So, we agreed to do a wire transfer. ((("wire transfer")))It took 16 days. First, they asked for my account number. Then, the next day they said they needed the SWIFT number. By that time, my bank was closed, so I couldn't get the SWIFT number. The next morning, I got the SWIFT number and I sent it to the Germans. By that time, their bank was closed. The next morning, they used the SWIFT number and discovered it was the wrong SWIFT number. It was the SWIFT number for US dollars, not for foreign currency. So, they sent me an email, but by that time my bank was closed. The next day, I got the other SWIFT number and I sent it to the Germans, but by that time their bank was closed. They sent me the wire. My bank took one look at this wire and said, "Bundesbank. Never heard of them. Sounds dodgy. Let's freeze this for 14 days, just in case it bounces.” This is the third largest central bank in the world. This is the German Federal Bank. They do not bounce checks. 14 days later—and this is the great part—they said, "Money held. Money released." They released 80 dollars of the total amount, which was a four-figure amount. 80 dollars. Why 80? What the hell is that? What am I going to do with that? Just hold all of it. Are you teasing me? This makes no sense.

=== The Problem with Traditional Banking Metaphors
This is what we're addressing with bitcoin. If you are introducing a new product in this market and you are a designer, which parts of this design metaphor do you want to re-use in your product? According to the bitcoin marketplace, all of them, so that you can persuade people that this is just like your bank. It doesn't have any of the good parts of a bank—like the ability to easily reverse transactions, to get a refund if you lose your private key. It doesn't have any of those. It also doesn't have any of the bad parts of banks, but we don't pay attention to that. So, we've created expectations that are entirely misleading.
____
"Bitcoin desperately needs design. It has been created by engineers and it is absolutely inscrutable."
____

=== Innovation, Design, and Adoption
Bitcoin desperately needs design. It has been created by engineers and it is absolutely inscrutable. But I have hope because we've done this before. I got on the internet in 1989, and at the time it was illegal to do commercial activities on the internet. It was owned by the National Science Foundation, and it was only for academics (or, let's say, 15-year-olds who happen to find the password to an academic system). At the time, DNS was still in its infancy. Most systems didn't really have DNS names assigned yet. It wasn't very well structured. A lot of the most interesting things you could only find via IP address. I walked around with a list of IP addresses in my wallet, so I had access to these things. In order to use it, it required UNIX command-line skills.

There was absolutely no way that was going to get used by my mom. My mom called me and told me her stereo was broken, and I tried to figure out why. She said, “It’s displaying an error message. It's blinking at me ‘0:00.’” It took me a few minutes to figure out that she had pulled the plug and the clock had reset. So, the clock was waiting to be set again and was blinking “0:00.” That's the person who I wanted to use the internet so we could talk, but that wasn't going to happen. It took almost exactly 20 years from the day I sent my first email to the day my mom sent her first email. In order to do so, a lot of things had to happen. Most importantly, the iPad. She was able to do it with a swipe of a finger, and that was the only thing that made it possible. There was no way _that_ internet in 1989 could be used by the mainstream. ((("adoption")))

==== UX and Society
There's this fantastic outtake from a morning TV show in 1994 in which the journalists are in a huddle just before the show. ((("internet")))((("innovation", "internet")))They are discussing their upcoming internet story, and they're trying to get their information right. One journalist is asking the other journalists, "So, wait, the internet is the thing with the ‘at’ sign?" "No, no, that's email. The internet is the thing with the ‘www,’ with the dots and the slashes." "I thought that was the email.” "No, that's the internet." "But isn't that the web?" So there's this circular discussion. A system designed by engineers. Inscrutable. Two things happened. One, we made the technology much easier to understand, much better, more polished. Another important thing happened: society moved. Today, the average person knows exactly the difference between an @ sign and a www, even though it's a horrible design. Society learned the language of the internet because it was valuable enough to learn the language of the internet.

____
"Society learned the language of the internet because it was valuable enough to learn the language of the internet."
____

While we made the internet easier, society caught up and also understood the really inscrutable parts of the internet. The same thing is happening with bitcoin. I go to mainstream conferences where they have never heard of bitcoin before and I say, "Listen, don't worry. Someone in your life can explain bitcoin to you. When they're done cleaning their room, ask them to teach you bitcoin.” Their 10-year-old will understand it. I've met kids that use web-based interfaces to create altcoins of their own.

One of the interesting questions I get often is "How many coins and currencies will there be?" The answer to that is exactly equivalent to "How many bloggers will there be on the internet?" All of us. All of them. Not hundreds of coins; thousands, tens of thousands of coins. When a 6-year-old can create a coin called Joeycoin to launch in his school as a popularity contest, the fact that that coin is also global, unforgeable, scalable, and can be used internationally doesn't matter to Joey, as long as his five friends really like to use Joeycoin. Unfortunately, a competitor, Mariacoin, is launched on the scene, and an old-fashioned currency war starts. This is going to happen. Part of the reason we know this is because children create currency. You leave children in a kindergarten by themselves, and they will invent currency—rubber bands, Pokémon cards, little cubes. They will start hoarding, trading, exchanging for favors, and then eventually getting into a fight over their imaginary currency that they just invented. This is a human experience.

_We_ just invented the world's most awesome currency. Your job now is to create the right design metaphors to make it work for everybody else.

Thank you.
