[preface]
== Foreword
_By Don Tapscott_

In early 2014, my son Alex and I began the research for our book _Blockchain Revolution_. I had been working on the 20th-anniversary edition of _The Digital Economy_ and reflecting on the last two decades and what's next. I had become fascinated by Bitcoin and cryptocurrencies. Meanwhile, Alex was an executive with the investment bank Canaccord Genuity. He noticed the growing enthusiasm of early-stage bitcoin and blockchain companies in 2013 and began leading his firm’s efforts in the space. During a father-son ski trip to Mont-Tremblant in early 2014, we brainstormed over dinner about collaborating on this topic and, to make a long story short, decided to write a book.

We were aware of the writings of Andreas M. Antonopoulos, and our work quickly drew us into the extensive collection of his speeches on YouTube. I remember watching and rewatching them for hours and taking extensive notes throughout. Both Alex and I were struck with the depth of his knowledge, his fluency explaining complex concepts, and his clarity of thinking. Here was someone who presents the most difficult of topics in simple terms, using strong analogies and with passion and insight in every talk. I remember thinking _how can this guy know so much about something so new?_

In https://www.youtube.com/watch?v=JP9-lAYngi4[one video in 2013] he was filmed talking to others around a table –- but YouTube revealed that tens of thousands of people had watched the discussion. In another, he showed great alacrity in the face of adversity, most memorably in a brilliant talk about https://www.youtube.com/watch?v=BT8FXQN-9-A[“Bitcoin Neutrality”] to a large convention hall with only a few people seated in it. When the camera zoomed in you might think he was talking to a full theatre based on his energy and expressiveness.

It was good he persevered. Fortunately, both these and other talks were captured by video and we can all benefit today. With the publication of _The Internet of Money_, tightly edited versions of these lectures are sure to be received thankfully by many, including me. The talks are each unique (no canned presentations here), unscripted, and compelling. There are few people who have the abilities to speak extemporaneously on any tough topic, let alone on this one.

The early days of most technological revolutions are dominated by the builders, and there is typically a dearth of deep conceptualizing and lucid explanation. After all, it took decades after the creation of the ARPANET -- the early incarnation of the internet -- for big thinkers to dig into the implications of what the first generation of the digital revolution might mean for our lives. So it was with the second era of the Internet -- the technology behind digital currencies. The first years of Bitcoin were dominated by developers and then speculators -- both practitioners, in a sense. Early advocates presented theories about how this new technology could free us from the shackles of government but the world needed more than ideological missives to understand the importance broader significance of crypto currencies. We also needed someone to explain how all this stuff worked.

Put simply, Andreas stepped up. In fact, I’ll bet history will remember that there was no one who played a more important role in the early days of explaining Bitcoin, what it is and what it means. Needless to say when it came to doing in-depth interviews of thought leaders for our own book, we pretty much started with Andreas.

Reading this collection of talks, it’s amazing to contemplate that Andreas was waxing poetic and profound years before hardly anyone had even heard of Bitcoin. However don’t read this for the historical record of a fertile mind. Rather, read it for its rich insights, which are equally relevant, if not more relevant, today.

Andreas was on to something big, early. Alex and I agree that a new kind of Internet is in the making. For the last decades we’ve had the Internet of Information, but today we’re witnessing the birth of the Internet of Value, or as Andreas calls it, The Internet of Money. Everyone, dear reader, needs to understand this revolution as its impact will surely be as great or greater than the first era's.

Parenthetically, let me note that, as a Canadian I’m a direct beneficiary of Andreas’ fertile mind. In March 2014, the Canadian Senate authorized the Standing Senate Committee on Banking, Trade and Commerce to study digital currencies, with a particular focus on their potential risks, threats and advantages. The Senate’s initial interest in the topic was negative, somewhat motivated by media reports about Bitcoin being used to launder money and commit crime. Andreas https://www.youtube.com/watch?v=GP_eT6E4os8[testified] before the committee and his session is now somewhat legendary in blockchain lore. As one Senator told me, “he blew our minds” (a tough thing to do for the gentlemen of this austere Canadian “Chamber of sober second thought”).

When all was said and done the Senate issued a stellar report that emphasized the positive opportunities and took a strong position against pre-mature regulation and interference in the blockchain revolution. Thank you, Andreas.

Enjoy this book. If you’re new to the topic, prepare to join Canada’s sober Senators and have your mind blown too. If you think you know all there is to know, prepare to be humbled and inspired. I am thankful Andreas took the time to capture these videos in text as this tome will make an important contribution to our mutual challenges of ensuring that this new Internet fulfills it’s enormous potential.

Don Tapscott, Lake of Bays, Ontario Canada. August 20, 2016.

_Don Tapscott is the author of 15 books on new technology in society, including *Paradigm Shift*, *Growing Up Digital*, *The Digital Economy*, *Wikinomics*, and most recently with his son Alex, *Blockchain Revolution: How the Technology Behind Bitcoin is Changing Money Business and the World*. He is the CEO of the think tank The Tapscott Group; an adjunct Professor at the Rotman School of Management, University of Toronto and an Associate of the Berkman Klein Center for Internet and Society at Harvard University._
