== Money as a Content Type

_Bitcoin South Conference; Queenstown, New Zealand; November 2014_

Video Link: https://www.youtube.com/watch?v=6vFgBGdmDgs

Good morning, everyone. What I want to talk about today is a new topic I've been working on: money as a content type. ((("money", "content type")))Bitcoin has introduced a fundamental transformation in how money is going to be viewed in the future by making money completely independent of the underlying transport medium and turning it into a stand-alone content type.

What do I mean by that? A bitcoin transaction is a signed data structure that can be executed anywhere in the world. ((("transaction")))A lot of people think that a bitcoin transaction has to be transmitted on the bitcoin network. That's not true. A bitcoin transaction has to reach the miners and be included in a block, but it doesn't need to be transmitted over the bitcoin network. There's nothing special about the bitcoin network. It just forwards transactions and blocks. A transaction can be transmitted over any form of communication medium.

One of the magic things about bitcoin is that the transaction doesn't incorporate security mechanisms itself. The security is in the proof of work provided by the miners, and the digital signature on the transaction is put there by end users with keys that they store. There's nothing sensitive or secret in the bitcoin transaction. ((("security")))Let me explain what I mean by that.

=== Credit Cards: Insecure by Design
If I go to a merchant today using a point-of-sale system and a credit card, what I am transmitting to the merchant (through a long series of intermediaries) is the credit card number, expiry date, and CCV2 code on the back of the card. I'm actually transmitting the secret keys. I'm transmitting the access codes to my account. That information is sensitive. If that information is captured, my account can be compromised. I can be charged again and again, either by the merchant or one of the intermediaries, or any hacker who has taken this information from any of the intermediaries. My credit card information needs to be very carefully protected. ((("security", "credit cards")))

From the moment the credit card comes out of my pocket until the money is in the merchant's account, it is transported across the network in a series of virtual armored cars. There's encryption from the point of sale to the merchant's back end. From the merchant’s back end, encryption through to Visa for batch processing. From Visa, encryption through to the originating bank and to the destination bank, encrypting this token at every step of the way because it is the secret key. If that encryption fails at any point in the chain, the security of my credit card is compromised.

That credit card is also stored at many of the points of transit. It's stored for historical purposes. Which is a terrible idea because that creates a centralized treasure trove, a stash for hackers to attack. We've seen this happen again and again. In the US, Target and Home Depot, two very large retailers, have had incidents where they've had 50 to 60 million credit cards stolen. ((("credit cards")))JPMorgan Chase had 75 million accounts compromised recently. All of these things are not happening because these companies are delinquent in protecting credit cards. ((("security", "breach")))

____
"There are really two types of companies out there: those that have failed to take the necessary action to secure the credit cards that you entrusted them with; and those that will soon fail to take the necessary security action to protect the credit cards you've entrusted them with...Credit cards are broken by design because the token itself is the secret key. If you transmit that token, you expose your entire account to risk."
____

There are really two types of companies out there: those that have failed to take the necessary action to secure the credit cards that you entrusted them with; and those that will soon fail to take the necessary security action to protect the credit cards you've entrusted them with. You've either been hacked or you will be hacked—those are the two categories. Nobody's immune to this. No one can invent a way to protect millions of secure access tokens from motivated attackers. It's impossible to do. We don't know how to do it. There is no information security trick that can protect for all possible types of attacks. Credit cards are broken by design because the token itself is the secret key. If you transmit that token, you expose your entire account to risk.

=== Bitcoin Transactions: Secure by Design
Bitcoin is fundamentally different. What I'm transmitting is not the key, but simply a signed message. It is an authorization. That authorization has two external references: (1) to where the money's coming from by referencing an unspent output on the blockchain, and (2) a reference to where I want to send the money -- by creating a new encumbrance, a new limitation on who can spend the money, usually a public key or bitcoin address. That transaction contains no sensitive data. If you steal the information in the transaction, all you know is which address the money came from, which address the money's going to, and how much. That's it. The signature reveals nothing. The addresses reveal nothing. There are no identifiers. You could take the transaction and print it out. You could post it on a billboard. You could shout it from the rooftop. A bitcoin transaction can be transmitted over completely unsecured Wi-Fi. By smoke signal. By light signal. With carrier pigeons. It doesn't matter. Nothing in that message can be compromised. ((("security", "authorization")))

____
"A bitcoin transaction can be transmitted over completely unsecured Wi-Fi. By smoke signal. By light signal. With carrier pigeons. It doesn't matter. Nothing in that message can be compromised."
____

=== Money as a Content Type
Most people don't realize what it means to convert money into a content type. We've taken the transaction, which is just 250 bytes, and we’ve separated it from the transport medium, so it doesn't depend on any underlying security. We've made it stand alone so that it can be independently verified by any node that has a full copy of the blockchain. Independently verified as spendable, authentic, and properly signed by _any_ system that has a full copy of the blockchain—in fact, even by systems that only have a partial copy of the blockchain. That transaction can be verified in seconds. All it has to do is reach one node in the network that can talk to miners. That's it. Once it's injected into the bitcoin network and once it propagates, you can be almost certain that the transaction will be included eventually and will become valid. If I look at any transaction, I can calculate if it has sufficient fees, and then I can make certain assumptions about how miners are going to treat that transaction because I know the rules by which they operate on a consensus network. I know that once the transaction is propagated enough, it will appear in a block near you, soon.

=== Stopping Bitcoin Transactions Is Impossible
There's nothing magical in a bitcoin transaction. Let's think about this for a second. How can you encode 250 bytes and transmit them across the network?

Someone recently asked me, and I get this question a lot, “Can't tyrannical governments block or ban the transmission of bitcoin transactions?” The answer is _no_, but I don't think people quite understand _why_ the answer is no. I'll give you a couple of theoretical examples to show what I mean. ((("censorship")))

==== Transmitting Bitcoin Transactions via Skype as Smileys
My first ridiculous example is the encoding of bitcoin transactions as emoticons or smileys in Skype. Skype has a 128-character emoji alphabet which allows you to send various frowny faces, smiley faces, thumbs up, thumbs down, sunny days, beating hearts, birthday cakes—you know, all of those kinds of things. Now, let's look at that from an information-content perspective. That's a character set, right? If I'm a computer scientist, I'm going to look at that and say, okay, I now have an encoding scheme. This would allow me to send a 250-byte transaction in about 500 characters. 500 smileys. A bitcoin transaction in smileys. ((("transactions", "as emoji")))

I can literally mathematically write a little script, it's two lines of Python probably. If you're really efficient, it's probably one line. No libraries needed. In the script, I can take the hexadecimal representation of a bitcoin transaction and encode it in emoticons. I can then copy that into a Skype window anywhere in the world. As long as the recipient who receives that string smileys types it into a decoder script and then simply injects it into the bitcoin network, that transaction will go through. The recipient could be a robot. The recipient could be an automated listening station that is designed to decode smileys into transactions and transmit them onto the bitcoin network.

Now, explain to me how anyone can make that stop, other than by shutting down Skype. If they shut down Skype, I'll use Facebook. If they shut down Facebook, I'll use Craigslist. If they shut down Craigslist, I'll put my transaction in a TripAdvisor review. If they shut down TripAdvisor, I'll post it as a comment in the history of a Wikipedia article. If they shut that down, I'll post it as the background of a JPEG image in my holiday snapshots.

____
"Money is now completely disconnected information content."
____

Money is now completely disconnected information content. There is absolutely nothing you can do to stop information from traveling from anywhere in the world to anywhere in the world when you have an abundance of fully interconnected multimedia communication mechanisms as we do today.

==== Transmitting Bitcoin Transactions via Shortwave Radio
Let's say we didn't have the internet. I came up with an even more ridiculous harebrained scheme, which is the transmission of bitcoin transactions over shortwave, frequency-hopping, burst radio. ((("transactions", "shortwave radio")))This is if you want to go completely guerrilla-style.

During the Second World War, in occupied France, the Allies dropped thousands of shortwave radios -- complete kits with little parachutes -- from airplanes, so that Partisans on the ground could hide these in barns, in tree hollows, in abandoned buildings, under bridges, and use them to communicate with various Allied command centers around Europe, from right under the nose of the occupying Nazi force. One of the things about shortwave radio is that not only do you have enormous range, but you can also, in certain frequencies, bounce off the stratosphere. At the time, they used this for voice communication or coded numbers communication, Morse code and various one-time pad encryption schemes.

Today, I can get a kit that allows me to connect a very simplistic shortwave radio transmitter to my laptop via USB. Now all I need is an antenna. The nice thing about that is that with shortwave radio, an antenna consists of a sufficiently long piece of metal -- a railway line, a clothesline, a broken-down electricity line, a fence line, a razor-wire fence. Which, I've noticed here in New Zealand you have lots of. It's right around those fuzzy white things that are everywhere -- the sheep.

Now, the transmission of a bitcoin transaction involves plugging in a laptop, attaching it to a fence post, pressing “enter,” and transmitting a burst transaction for 25 seconds. As long as there's a receiving station somewhere within the surrounding thousand miles that is connected to the bitcoin network -- and you can hide the receiving station anywhere you want, it's a passive listener, it can't be triangulated -- that listening device can inject the transaction into the network. If I'm the guerrilla and I want to buy something, I construct the transaction offline, and when I'm ready, run out into the middle of the field, clamp my transmitter onto a clothesline, press “enter,” transmit for 25 seconds, pack up my gear, and disappear into the forest. How the hell do you stop that? You don't. That's the simple answer, you don't. But that's just the beginning.

=== Separating the Medium and the Message
Once you realize that money has become a content type, that transactions have been disconnected from the medium, some really important secondary characteristics emerge. You see, the medium is the message, as someone famous once said. The primary reason the medium is the message is because the medium constrains, transforms, and in many cases, distorts the message. ((("medium", "message")))

When your medium is TV, your message is 18 minutes long, interrupted by advertising slots. That is your message; there is no other format you can fit there. So, you make a message that fits that medium. And you start assigning the value of your message based on the mistaken assumption that it is equivalent to the cost of production. TV, for example, imposes a certain cost to producing video. People who are in that business make the mistaken assumption that the cost of producing TV is the same as the value of that show. The more you spend on it, the more valuable it is. ((("value of content", "cost of production")))

You can imagine their horror when something like YouTube comes along and drops the cost of production to zero. What do you think is the immediate assumption that people make in that industry? If the cost is zero, then the content is worthless. That is a fundamental misunderstanding of what happens when you separate the content from the medium. By separating the message from the medium, your perception of value shifts from the cost of production to the value it has to the consumer when they consume it. ((("value of content", "value to consumer")))

____
"When the cost of printing is astronomical and the means of printing are available only to a select few, the only thing you print is Gutenberg Bibles."
____

Let me give you an even older example. When the cost of printing is astronomical and the means of printing are available only to a select few, the only thing you print is Gutenberg Bibles. The medium defines the range of expression of the message, and constrains it only to the most grandiose and important messages that society has. It limits the range of expression by imposing enormous costs of production.

What do you think Gutenberg would have thought of Twitter, which takes the cost of production to zero, makes it available universally, ubiquitously, and for free. You go from printing the Gutenberg Bible to responding to a tweet with one of my favorite expressions, the three-character opinion “SMH” -- which means “shaking my head.” When “Professor Bitcorn" says, "Bitcoin is going to zero,” I can express my entire range of opinion and thoughtful analysis as _shakes head with facepalm_. Three characters, and I have expressed my opinion to the world. If you look at that from an objective perspective, surely that message is worthless. When you make the mistaken assumption that if the cost of production is zero, and the message appears trivial on its face, then the entire combination of medium plus message must be worthless, must be trivial, must have no value -- that's a mistake that people have made at every turn in history.

When Twitter first came out, people assumed it would only be used for the trivial. And yet, a year ago I was watching _CNN International_ covering the Egyptian revolution, and they were live-streaming tweets from Egyptian revolutionaries on the streets of Cairo, giving live reports about what is happening minute-by-minute. CNN anchors are doing nothing. They're pointing at the screen and saying, "Look, we have another tweet. And here's another tweet from someone we don't know. Here's another tweet." They've been reduced to the role of a TV show model saying, "And this wonderful refrigerator will be yours if you win the prize behind door number one.” I find it extremely gratifying to watch one of these talking heads, like Anderson Cooper, basically reduced to reading tweets off a screen.

Because they mocked it. They made the mistaken assumption that if the cost of production is zero, the value of the message is zero. They confused the medium for the message. They made the mistaken assumption that their control over the medium was the source of quality. And long after quality disappeared, they clung to control and thought that control was the only way to achieve quality, and if you removed control, you removed quality. That is stinky, unabashed elitism at its absolute worst. It assumes that the gatekeepers are the source of quality, when all they are is gatekeepers. They assume that the fact that they have the expensive medium means that the message is worth listening to.

____
"They made the mistaken assumption that if the cost of production is zero, the value of the message is zero. They confused the medium for the message. They made the mistaken assumption that their control over the medium was the source of quality. And long after quality disappeared, they clung to control..."
____

The moment you tear that message away from the medium and you open it up to an entire range of expression, yes, it will express the most trivial messages of your culture, including “SMH.” But it will also express the most interesting messages of your culture, eventually.

Today in US schools, children read _The Federalist Papers_, which is a collection of public essays written in the 18th century by some of the founding fathers debating the meaning of democracy for the new republic. In 100 years, people will be reading _The Federalist Tweets of the Cairo Revolution_. That's not an insane idea. That is the path of human civilization. We've seen this happen again and again.

Now, they mock Twitter as trivial because they don't understand the distinction between message and medium. ((("medium", "message")))TV was once mocked as a trivial pastime because it obscured the art of cinematography. Cinematography was a trivial pastime because it cheapened and vulgarized the art of the theater. The theater was a vulgar and cheap pastime of Victorians because it trivialized the great dramatic plays of the Romans and the Ancient Greeks. You keep going down this path and you'll eventually arrive at Aristotle saying that philosophy is dead because nowadays the kids all want to watch dramatic presentations instead of reading their philosophy books. He probably complained about their long hair, too. Every generation mistakes the medium for value and considers the next iteration of the medium—that widens access, that opens availability, that broadens the range of expression—they consider that medium trivial, vulgar, cheapening the message.

____
"Every generation mistakes the medium for value and considers the next iteration of the medium—that widens access, that opens availability, that broadens the range of expression—they consider that medium trivial, vulgar, cheapening the message."
____

What they don't understand is when you cheapen the medium, you release the message and you elevate it. You are able now to express a broad range of messages. Yes, the first ones will be trivial. The reason they'll be trivial is because the previous medium didn't allow for that expression. It didn't have within it the ability to have that expression. Yes, you will have the “SMH.” You'll also have live tweets from the Cairo revolution. ((("innovation", "new medium")))By the time they figure that out, the new medium _is_ the quality message. Then, we can turn around and call the next one vulgar and cheap.

=== Money Is the Message, Now Freed from the Medium
Money is a content type, and we just wrenched it free from the medium. The medium has been a series of interconnected networks that segregate money by size and recipient. We have payment networks for small money. We have payment networks for large money. We have payment networks for fast money. We have payment networks for slow money. Payment networks for businesses to pay businesses. Payment networks for governments to pay governments. Payment networks for consumers to pay businesses. Payment networks for consumers to pay consumers. ((("network", "payment"))) Oh wait, we don't really have those. We don't have payment networks for consumers to pay consumers. We don't have payment networks to do small payments because the traditional medium does not allow that range of expression.

____
"Money is a content type, and we just wrenched it free from the medium."
____

I cannot send you 20 cents across the world, from one individual to another individual, because the medium constrains the message. The cost of production does not allow me to express that range of transactional expression. But now we have separated the message from the medium. We have created money as a content type. That money is now able, at near zero production cost, to express the entire range of transactional expression—from the tiny to the enormous, from consumer to consumer, from government to government. ((("production cost")))

What happens next? The gatekeepers tell you that this network is not serious. The gatekeepers confuse their payment-network cost for the value of their service. The gatekeepers of the old payment networks will tell you that this new form of payment is vulgar and cheap. It is something that is only used for trivialities. All of the very serious people will remain on the solid, quality payment networks of the past. Because if they can control and restrict the range of expression, they think that means it's quality. It's not. It's just an inflated cost of production. It's bare naked elitism at its worst. They cling to the medium and fail to see that now the message can be transported over any medium at zero cost, instantaneously.

What is the first use of this new model? What is the first use of this new messaging medium? Now we can send trivial payments. I get tips on Twitter. That's a demonstration I can make that clearly shows people the difference. I can do something I could not do before. But to most people, that's trivial. To most people, the fact that I'm showing them the bottom of the range of expression simply reinforces the idea that this is a cheap and vulgar medium. What they fail to grasp is that this medium is not just for the trivial; it spans the entire range of transactional expression from the trivial to the enormous.

____
"The blockchain can encompass the entire range of transactional expression, from the 10-cent tweet to the $100 billion debt settlement."
____

One day, a country will pay its oil bill on the blockchain. One day, you might buy a multinational company on the blockchain. One day, you might sell an aircraft carrier, hopefully for scrap metal, on the blockchain. The blockchain can encompass the entire range, from the 10-cent tweet to the $100 billion debt settlement. We just haven't noticed yet. It can do so without any constraint imposed by the underlying medium. This isn't just a matter of the fact that the transaction as a content type can be transported over Skype smileys. That's simply a symptom of the fact that we have released all of the constraints of the underlying transport medium. We have made content king. ((("content")))

=== Grand Arc of Technology
When content begins as the domain of exclusivity, elitism, and limited access, it is used by grandmasters to create masterpieces. The Gutenberg Bible. The first photographs. The landing on the moon, televised for the first time. The great movies of the past. Masterpieces made by grandmasters. ((("technology", "grand arc")))

Then the medium changes because the technology becomes more available. People start using it for a broader range of expression, but the gatekeepers still cling to the old ideas. They still try to do the grandiose with their medium. They print hardback, heavy, leather-bound books—_Principia Mathematica_. Then the medium opens up again and things become softcover, and photographs become available to the everyday person in 24 exposures. The gatekeepers of the past still cling to the past, but now they can't really pretend that it's grandiose, so they just do grandstanding. They say, “There's a certain _je ne sais quoi_ to film.” “There's a certain quality to vinyl that CDs will never capture.” “A TV anchor really has authority. Don't you remember Walter Cronkite?” “A newspaper is the source of authoritative opinion, and it really is worth the paper it's printed on." Grandstanding. The grandiosity is gone. The quality is gone. Now, it's just a matter of clinging to the control and pretending that control is still quality.

Finally, in this grand arc of technology, the technology reaches the final stage. In that final stage, the only people who still believe it's grand are grandparents. In the grand arc of technology, what started out as a masterpiece is now only consumed by those in the last stages of their lives. The first checks written out were used by royalty to fund great ventures like the East India Company to open the spice roads and trade routes to the East. In those days, only royals had checkbooks. Today, if you go into a supermarket and the grandmother, bless her heart, in front of you in the line opens up her purse and pulls out the checkbook, 15 people in line are going to groan audibly as they realize it's going to take 15 minutes to write out that transaction. There's nothing left of the grandiosity of funding the East India Company when you're buying beans and toast with a checkbook in a supermarket. It's the final stage.

The only people watching _Fox News_ now are grandparents, because we all get our news on the internet. What was once trivial is now our source of authoritative news and information. You can't explain that to the old guard. We read our books electronically. Some people say, "There's something about the feel of paper." Yes. It's too heavy to carry 20 books in your bag, and I read 20 books in four or five weeks, so I need to carry that many. There's nothing about the feel of paper; that's clinging to the past.

____
"As we move into this world where money is a content type, the gatekeepers of the old payment systems will cling to the illusion that traditional banking is quality. That the gatekeepers are the quality. But that's not where the quality is."
____

As we move into this world where money is a content type, the gatekeepers of the old payment systems will cling to the illusion that traditional banking is quality. That the gatekeepers are the quality. That the quality is inherent in the gatekeeping—in the control, in the censorship, in the limitations. But that's not where the quality is. We're moving on and opening up the range of expression that is possible with money to unimaginable levels, to things that have never happened before. They'll still cling to their ideas of grandiosity: the great old banks with the vaulted ceilings and the chromed vaults that are empty, where you can get guided tours on Sundays, to look at what banks used to be like. You can go into cities around the world and the great vaults of the great old banks are now bars where you can get a cocktail in the vault, because banks can't even afford to have those buildings anymore. They serve no purpose other than grandiosity. They'll still try to persuade you that through their control, they protect you from evil, from terrorists, from money launderers. All they're doing is protecting their own incumbency from competition.

We have now separated the message from the medium. Money is now a content type, and we're never going back.

Thank you.



_Note from Andreas to the reader: In this talk I foolishly attempted to improvise math in my head while delivering the talk. I am not very good at math. Turns out I am even worse at improv-math. None of my bad math changes the point I was making, but it's been edited out for accuracy and to protect my ego. Ssssh! Don't tell anyone I suck at improv-math._
